from enum import IntEnum, auto


class Network(IntEnum):
    # Client -> Server
    REQUEST_CONNECT = 0

    REQUEST_PLAYER_MOVE = 1

    REQUEST_PLAYER_SHOOT = 2
    REQUEST_PLAYER_DAMAGE = 3
    REQUEST_PLAYER_RESPAWN = 4
    REQUEST_PLAYER_CHANGE_TEAM = 5
    REQUEST_PLAYER_SONIC = 6

    REQUEST_PLAYER_UPDATE = 7
    CHAT_MESSAGE = 100
    PING = 254

    # Server -> Client
    PLAYER_CONNECTED = 100
    OTHER_PLAYER_CONNECTED = 101
    OTHER_PLAYER_DISCONNECTED = 102

    PLAYER_MOVED = 103          
    OTHER_PLAYER_MOVED = 104

    PLAYER_SHOOT = 105
    OTHER_PLAYER_SHOOT = 106
    PLAYER_DAMAGED = 107
    PLAYER_KILLED = 108
    PLAYER_RESPAWNED = 109
    PLAYER_CHANGED_TEAM = 110
    PLAYER_SONICKED = 111

    PLAYER_UPDATED = 112 
    PLAYER_SETUP = 113

    RANKING_UPDATED = 199
    CHAT_RECEIVED = 200
    PONG = 255
