from enum import IntEnum, auto


class Network(IntEnum):
    # Client -> Server
    REQUEST_AUTH = 0
    REQUEST_CONNECTS = 1

    REQUEST_PLAYER_MOVE = 2

    REQUEST_PLAYER_SHOOT = 3
    REQUEST_PLAYER_DAMAGE = 4
    REQUEST_PLAYER_RESPAWN = 5
    REQUEST_PLAYER_CHANGE_TEAM = 6
    REQUEST_PLAYER_SONIC = 7

    REQUEST_PLAYER_UPDATE = 8
    
    CHAT_MESSAGE = 100
    PING = 254

    # Server -> Client
    
    AUTH_SUCCESS = 65
    AUTH_FAIL = 66
    PLAYER_CONNECTED = 67
    OTHER_PLAYER_CONNECTED = 101
    OTHER_PLAYER_DISCONNECTED = 102

    PLAYER_MOVED = 103          
    #OTHER_PLAYER_MOVED = 104

    PLAYER_SHOOT = 105
    #OTHER_PLAYER_SHOOT = 106
    #PLAYER_DAMAGED = 107
    #PLAYER_KILLED = 108
    #PLAYER_RESPAWNED = 109
    #PLAYER_CHANGED_TEAM = 110
    PLAYER_SONICKED = 111

    PLAYER_UPDATED = 112 
    PLAYER_SETUP = 113
    
    
    RAT_ATTACKED = 198
    RANKING_UPDATED = 199
    CHAT_RECEIVED = 200
    PONG = 255
